#!/bin/bash

#This defines the compression level for gzip at the end of the script, acceptable values are between 1-9
export COMPRESSION_LEVEL=-6

#Will be used in future releases
export EXTERNAL_STORAGE=

#Will be used in future releases
export DVD_DRIVE=/mnt/cdrom

#Will be used in future releases
export AUTO_BURN=false

#Will be used in future releases
export AUTO_CP_TO_EXTERN=false

#Path to the file which lists all files to be backed up
export USER_DEFINED_BACKUPS=$HOME/.config/tar-pit/backup.txt

#List of all files in $HOME
export DEFAULT_BACKUPS=$HOME/.config/tar-pit/home_index.txt

#Names the tar and tar.gz files created
export TAR=$(date '+%m-%d-%y').tar
export COMP_TAR=$(date '+%m-%d-%y').tar.gz

#Directory where output files are stored
export TARGET=$HOME/tar-pit
